// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"

	p2p "github.com/cometbft/cometbft/p2p"
)

// ConnectionAuthenticator is an autogenerated mock type for the ConnectionAuthenticator type
type ConnectionAuthenticator struct {
	mock.Mock
}

// SecureInbound provides a mock function with given fields: _a0, _a1
func (_m *ConnectionAuthenticator) SecureInbound(_a0 context.Context, _a1 net.Conn) (p2p.AuthenticatedConnection, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SecureInbound")
	}

	var r0 p2p.AuthenticatedConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, net.Conn) (p2p.AuthenticatedConnection, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, net.Conn) p2p.AuthenticatedConnection); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(p2p.AuthenticatedConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, net.Conn) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecureOutbound provides a mock function with given fields: _a0, _a1, _a2
func (_m *ConnectionAuthenticator) SecureOutbound(_a0 context.Context, _a1 net.Conn, _a2 p2p.ID) (p2p.AuthenticatedConnection, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SecureOutbound")
	}

	var r0 p2p.AuthenticatedConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, net.Conn, p2p.ID) (p2p.AuthenticatedConnection, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, net.Conn, p2p.ID) p2p.AuthenticatedConnection); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(p2p.AuthenticatedConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, net.Conn, p2p.ID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewConnectionAuthenticator creates a new instance of ConnectionAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionAuthenticator {
	mock := &ConnectionAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
